services:
  bot:
    secrets:
      - source: telegram_token
        target: MTLA_JOIN_BOT_TELEGRAM_TOKEN

secrets:
  telegram_token:
    file: ${MTLA_JOIN_BOT_TELEGRAM_TOKEN_FILE}
    name: mtla_join_bot_telegram_token
